### ISSUE TITLE
panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by ordian** [pyroscope-io/pyroscope-rs#12]
`pyroscope-0.3.0/src/backends/pprof.rs:108`
https://github.com/pyroscope-io/pyroscope-rs/blob/c659d0bffe624150c6a69be29f29162f4de2d57c/src/backends/pprof.rs#L108

**Comment by omarabid** [comment]
@ordian Can you give more context how this was triggered if possible? (platform/code profiled).

**Comment by drahnr** [comment]
Hey @omarabid we're test running it using the following PR https://github.com/paritytech/polkadot/pull/4871
