### ISSUE TITLE
Combine multiple ruby requests into one pprof file

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope-rs#52]
Right now when using the ruby gem multiple tags are sent in multiple requests, but we should combine them into one (ideally pprof). 

@petethepig will provide more info here later

**Comment by petethepig** [comment]
## Some helpful tips on pprof:

We have docs on how to ingest pprof into pyroscope [here](https://pyroscope.io/docs/server-api-reference/#pprof-format).

### Relations Diagram
![pprof dot](https://user-images.githubusercontent.com/662636/181865354-43dbaa32-3c0f-4924-b4a6-95d093d0e97e.svg)

pprof is basically a protobuf schema

* 1 profile has multiple `samples`
* each `sample` references a `location` and links it to `labels` (labels = tags)
* each location is a collection of lines
* each line links to a function and has a line number
* each function has multiple strings such as `name`, `filename`, etc
* all strings are encoded in a `strings_table` and referenced in other places via integers

---

You can see the pprof structure in json format using [this tool from our main repo](https://github.com/pyroscope-io/pyroscope/blob/main/scripts/pprof-view/main.go) (figured it might be useful for debugging):
```shell
cat pkg/convert/testdata/cpu.pprof | go run scripts/pprof-view/main.go
```

Here's what the output looks like:
https://gist.github.com/petethepig/e41226414e3f54a7c0eedb24c5a334da

**Comment by korniltsev** [comment]
implemented in https://github.com/pyroscope-io/pyroscope-rs/pull/60
