### ISSUE TITLE
Add support for adhoc profiling mode

### ISSUE THREAD

**Issue by abeaumont** [pyroscope-io/pyroscope-rs#8]
It'd be nice to make the integration work with [adhoc profiling mode](https://pyroscope.io/blog/pyroscope-adhoc-profiling/).
In order to do so, the integration should be able to override the server address with the value in the `PYROSCOPE_ADHOC_SERVER_ADDRESS` environment variable, if it's defined.

Some reference info:
- [documentation for adhoc support in HTTP API integrations](https://github.com/pyroscope-io/docs/pull/38)
- [adhoc profiling mode support in Java integration](https://github.com/pyroscope-io/pyroscope-java/pull/5)

**Comment by omarabid** [comment]
@abeaumont I'm a bit confused. What's the purpose of `PYROSCOPE_ADHOC_SERVER_ADDRESS` if the data is going to be saved locally?

**Comment by petethepig** [comment]
We're not going to implement it any time soon, so closing the issue.
