### ISSUE TITLE
Not working with Ruby 3.2.0 and higher

### ISSUE THREAD

**Issue by AnotherRegularDude** [pyroscope-io/pyroscope-rs#80]
**Describe the bug you encountered:**

When starting a server on Ruby 3.2, pyroscope writes an error in the logs that the current version of Ruby is not supported: `rails thread '<unnamed>' panicked at 'The target process's Ruby version is not supported yet. In the meantime, you can try using --force-version 3.2.0`
In this case, the application works as expected, except that nothing is sent to the pyroscope server.
...

**What did you expect to happen instead?**

Pyroscope works with Ruby version 3.2.

...

**How did you install `pyroscope-rs`?**

Using ruby gem from there https://rubygems.org/gems/pyroscope

---

Pyroscope gem version: 0.5.1
Ruby version: 3.2.0
OS: Debian
Also, Ruby running with enabled JIT.

**Comment by korniltsev** [comment]
Yeah, I will update rbspy shortly

**Comment by korniltsev** [comment]
or not so shortly.. I will need to figure out how to update our rbspy fork.
I will keep you updated.

**Comment by AnotherRegularDude** [comment]
Hi
I see that the PR is merged =)
Does it make sense now to build a gem from a master and build binary in our CI?
Or you'll soon push the gem to rubygems.

**Comment by AnotherRegularDude** [comment]
Oh, I see now
Thank you!

**Comment by korniltsev** [comment]
fixed in 0.5.2 gem

**Comment by AnotherRegularDude** [comment]
Working perfectly

Thank you =)
